/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PortalIndexRouteImport } from './routes/portal/index'
import { Route as AuthenticatedSettingsIndexRouteImport } from './routes/_authenticated/settings/index'
import { Route as AuthenticatedSalesIndexRouteImport } from './routes/_authenticated/sales/index'
import { Route as AuthenticatedProfileIndexRouteImport } from './routes/_authenticated/profile/index'
import { Route as AuthenticatedInventoryIndexRouteImport } from './routes/_authenticated/inventory/index'
import { Route as AuthenticatedDashboardIndexRouteImport } from './routes/_authenticated/dashboard/index'
import { Route as AuthenticatedClientsIndexRouteImport } from './routes/_authenticated/clients/index'
import { Route as AuthRecoveryPasswordIndexRouteImport } from './routes/_auth/recovery-password/index'
import { Route as AuthLoginIndexRouteImport } from './routes/_auth/login/index'
import { Route as AuthenticatedSalesNewIndexRouteImport } from './routes/_authenticated/sales/new/index'
import { Route as AuthenticatedInventoryOperationsIndexRouteImport } from './routes/_authenticated/inventory/operations/index'
import { Route as AuthenticatedInventoryNewIndexRouteImport } from './routes/_authenticated/inventory/new/index'
import { Route as AuthenticatedClientsNewIndexRouteImport } from './routes/_authenticated/clients/new/index'
import { Route as AuthenticatedInventoryOperationsNewRouteImport } from './routes/_authenticated/inventory/operations/new'
import { Route as AuthenticatedInventoryOperationsIdRouteImport } from './routes/_authenticated/inventory/operations/$id'
import { Route as AuthenticatedInventoryUpdateIdIndexRouteImport } from './routes/_authenticated/inventory/update/$id/index'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalIndexRoute = PortalIndexRouteImport.update({
  id: '/portal/',
  path: '/portal/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsIndexRoute =
  AuthenticatedSettingsIndexRouteImport.update({
    id: '/settings/',
    path: '/settings/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSalesIndexRoute = AuthenticatedSalesIndexRouteImport.update({
  id: '/sales/',
  path: '/sales/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileIndexRoute =
  AuthenticatedProfileIndexRouteImport.update({
    id: '/profile/',
    path: '/profile/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInventoryIndexRoute =
  AuthenticatedInventoryIndexRouteImport.update({
    id: '/inventory/',
    path: '/inventory/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardIndexRoute =
  AuthenticatedDashboardIndexRouteImport.update({
    id: '/dashboard/',
    path: '/dashboard/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedClientsIndexRoute =
  AuthenticatedClientsIndexRouteImport.update({
    id: '/clients/',
    path: '/clients/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthRecoveryPasswordIndexRoute =
  AuthRecoveryPasswordIndexRouteImport.update({
    id: '/recovery-password/',
    path: '/recovery-password/',
    getParentRoute: () => AuthRouteRoute,
  } as any)
const AuthLoginIndexRoute = AuthLoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthenticatedSalesNewIndexRoute =
  AuthenticatedSalesNewIndexRouteImport.update({
    id: '/sales/new/',
    path: '/sales/new/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInventoryOperationsIndexRoute =
  AuthenticatedInventoryOperationsIndexRouteImport.update({
    id: '/inventory/operations/',
    path: '/inventory/operations/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInventoryNewIndexRoute =
  AuthenticatedInventoryNewIndexRouteImport.update({
    id: '/inventory/new/',
    path: '/inventory/new/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedClientsNewIndexRoute =
  AuthenticatedClientsNewIndexRouteImport.update({
    id: '/clients/new/',
    path: '/clients/new/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInventoryOperationsNewRoute =
  AuthenticatedInventoryOperationsNewRouteImport.update({
    id: '/inventory/operations/new',
    path: '/inventory/operations/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInventoryOperationsIdRoute =
  AuthenticatedInventoryOperationsIdRouteImport.update({
    id: '/inventory/operations/$id',
    path: '/inventory/operations/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInventoryUpdateIdIndexRoute =
  AuthenticatedInventoryUpdateIdIndexRouteImport.update({
    id: '/inventory/update/$id/',
    path: '/inventory/update/$id/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/portal/': typeof PortalIndexRoute
  '/login/': typeof AuthLoginIndexRoute
  '/recovery-password/': typeof AuthRecoveryPasswordIndexRoute
  '/clients/': typeof AuthenticatedClientsIndexRoute
  '/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/inventory/': typeof AuthenticatedInventoryIndexRoute
  '/profile/': typeof AuthenticatedProfileIndexRoute
  '/sales/': typeof AuthenticatedSalesIndexRoute
  '/settings/': typeof AuthenticatedSettingsIndexRoute
  '/inventory/operations/$id': typeof AuthenticatedInventoryOperationsIdRoute
  '/inventory/operations/new': typeof AuthenticatedInventoryOperationsNewRoute
  '/clients/new/': typeof AuthenticatedClientsNewIndexRoute
  '/inventory/new/': typeof AuthenticatedInventoryNewIndexRoute
  '/inventory/operations/': typeof AuthenticatedInventoryOperationsIndexRoute
  '/sales/new/': typeof AuthenticatedSalesNewIndexRoute
  '/inventory/update/$id/': typeof AuthenticatedInventoryUpdateIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/portal': typeof PortalIndexRoute
  '/login': typeof AuthLoginIndexRoute
  '/recovery-password': typeof AuthRecoveryPasswordIndexRoute
  '/clients': typeof AuthenticatedClientsIndexRoute
  '/dashboard': typeof AuthenticatedDashboardIndexRoute
  '/inventory': typeof AuthenticatedInventoryIndexRoute
  '/profile': typeof AuthenticatedProfileIndexRoute
  '/sales': typeof AuthenticatedSalesIndexRoute
  '/settings': typeof AuthenticatedSettingsIndexRoute
  '/inventory/operations/$id': typeof AuthenticatedInventoryOperationsIdRoute
  '/inventory/operations/new': typeof AuthenticatedInventoryOperationsNewRoute
  '/clients/new': typeof AuthenticatedClientsNewIndexRoute
  '/inventory/new': typeof AuthenticatedInventoryNewIndexRoute
  '/inventory/operations': typeof AuthenticatedInventoryOperationsIndexRoute
  '/sales/new': typeof AuthenticatedSalesNewIndexRoute
  '/inventory/update/$id': typeof AuthenticatedInventoryUpdateIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteRouteWithChildren
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/portal/': typeof PortalIndexRoute
  '/_auth/login/': typeof AuthLoginIndexRoute
  '/_auth/recovery-password/': typeof AuthRecoveryPasswordIndexRoute
  '/_authenticated/clients/': typeof AuthenticatedClientsIndexRoute
  '/_authenticated/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/_authenticated/inventory/': typeof AuthenticatedInventoryIndexRoute
  '/_authenticated/profile/': typeof AuthenticatedProfileIndexRoute
  '/_authenticated/sales/': typeof AuthenticatedSalesIndexRoute
  '/_authenticated/settings/': typeof AuthenticatedSettingsIndexRoute
  '/_authenticated/inventory/operations/$id': typeof AuthenticatedInventoryOperationsIdRoute
  '/_authenticated/inventory/operations/new': typeof AuthenticatedInventoryOperationsNewRoute
  '/_authenticated/clients/new/': typeof AuthenticatedClientsNewIndexRoute
  '/_authenticated/inventory/new/': typeof AuthenticatedInventoryNewIndexRoute
  '/_authenticated/inventory/operations/': typeof AuthenticatedInventoryOperationsIndexRoute
  '/_authenticated/sales/new/': typeof AuthenticatedSalesNewIndexRoute
  '/_authenticated/inventory/update/$id/': typeof AuthenticatedInventoryUpdateIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/portal/'
    | '/login/'
    | '/recovery-password/'
    | '/clients/'
    | '/dashboard/'
    | '/inventory/'
    | '/profile/'
    | '/sales/'
    | '/settings/'
    | '/inventory/operations/$id'
    | '/inventory/operations/new'
    | '/clients/new/'
    | '/inventory/new/'
    | '/inventory/operations/'
    | '/sales/new/'
    | '/inventory/update/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/portal'
    | '/login'
    | '/recovery-password'
    | '/clients'
    | '/dashboard'
    | '/inventory'
    | '/profile'
    | '/sales'
    | '/settings'
    | '/inventory/operations/$id'
    | '/inventory/operations/new'
    | '/clients/new'
    | '/inventory/new'
    | '/inventory/operations'
    | '/sales/new'
    | '/inventory/update/$id'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/_authenticated'
    | '/portal/'
    | '/_auth/login/'
    | '/_auth/recovery-password/'
    | '/_authenticated/clients/'
    | '/_authenticated/dashboard/'
    | '/_authenticated/inventory/'
    | '/_authenticated/profile/'
    | '/_authenticated/sales/'
    | '/_authenticated/settings/'
    | '/_authenticated/inventory/operations/$id'
    | '/_authenticated/inventory/operations/new'
    | '/_authenticated/clients/new/'
    | '/_authenticated/inventory/new/'
    | '/_authenticated/inventory/operations/'
    | '/_authenticated/sales/new/'
    | '/_authenticated/inventory/update/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  PortalIndexRoute: typeof PortalIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/': {
      id: '/portal/'
      path: '/portal'
      fullPath: '/portal/'
      preLoaderRoute: typeof PortalIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings/': {
      id: '/_authenticated/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthenticatedSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sales/': {
      id: '/_authenticated/sales/'
      path: '/sales'
      fullPath: '/sales/'
      preLoaderRoute: typeof AuthenticatedSalesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile/': {
      id: '/_authenticated/profile/'
      path: '/profile'
      fullPath: '/profile/'
      preLoaderRoute: typeof AuthenticatedProfileIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/inventory/': {
      id: '/_authenticated/inventory/'
      path: '/inventory'
      fullPath: '/inventory/'
      preLoaderRoute: typeof AuthenticatedInventoryIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/': {
      id: '/_authenticated/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AuthenticatedDashboardIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/clients/': {
      id: '/_authenticated/clients/'
      path: '/clients'
      fullPath: '/clients/'
      preLoaderRoute: typeof AuthenticatedClientsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_auth/recovery-password/': {
      id: '/_auth/recovery-password/'
      path: '/recovery-password'
      fullPath: '/recovery-password/'
      preLoaderRoute: typeof AuthRecoveryPasswordIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/login/': {
      id: '/_auth/login/'
      path: '/login'
      fullPath: '/login/'
      preLoaderRoute: typeof AuthLoginIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_authenticated/sales/new/': {
      id: '/_authenticated/sales/new/'
      path: '/sales/new'
      fullPath: '/sales/new/'
      preLoaderRoute: typeof AuthenticatedSalesNewIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/inventory/operations/': {
      id: '/_authenticated/inventory/operations/'
      path: '/inventory/operations'
      fullPath: '/inventory/operations/'
      preLoaderRoute: typeof AuthenticatedInventoryOperationsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/inventory/new/': {
      id: '/_authenticated/inventory/new/'
      path: '/inventory/new'
      fullPath: '/inventory/new/'
      preLoaderRoute: typeof AuthenticatedInventoryNewIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/clients/new/': {
      id: '/_authenticated/clients/new/'
      path: '/clients/new'
      fullPath: '/clients/new/'
      preLoaderRoute: typeof AuthenticatedClientsNewIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/inventory/operations/new': {
      id: '/_authenticated/inventory/operations/new'
      path: '/inventory/operations/new'
      fullPath: '/inventory/operations/new'
      preLoaderRoute: typeof AuthenticatedInventoryOperationsNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/inventory/operations/$id': {
      id: '/_authenticated/inventory/operations/$id'
      path: '/inventory/operations/$id'
      fullPath: '/inventory/operations/$id'
      preLoaderRoute: typeof AuthenticatedInventoryOperationsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/inventory/update/$id/': {
      id: '/_authenticated/inventory/update/$id/'
      path: '/inventory/update/$id'
      fullPath: '/inventory/update/$id/'
      preLoaderRoute: typeof AuthenticatedInventoryUpdateIdIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthRouteRouteChildren {
  AuthLoginIndexRoute: typeof AuthLoginIndexRoute
  AuthRecoveryPasswordIndexRoute: typeof AuthRecoveryPasswordIndexRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthLoginIndexRoute: AuthLoginIndexRoute,
  AuthRecoveryPasswordIndexRoute: AuthRecoveryPasswordIndexRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedClientsIndexRoute: typeof AuthenticatedClientsIndexRoute
  AuthenticatedDashboardIndexRoute: typeof AuthenticatedDashboardIndexRoute
  AuthenticatedInventoryIndexRoute: typeof AuthenticatedInventoryIndexRoute
  AuthenticatedProfileIndexRoute: typeof AuthenticatedProfileIndexRoute
  AuthenticatedSalesIndexRoute: typeof AuthenticatedSalesIndexRoute
  AuthenticatedSettingsIndexRoute: typeof AuthenticatedSettingsIndexRoute
  AuthenticatedInventoryOperationsIdRoute: typeof AuthenticatedInventoryOperationsIdRoute
  AuthenticatedInventoryOperationsNewRoute: typeof AuthenticatedInventoryOperationsNewRoute
  AuthenticatedClientsNewIndexRoute: typeof AuthenticatedClientsNewIndexRoute
  AuthenticatedInventoryNewIndexRoute: typeof AuthenticatedInventoryNewIndexRoute
  AuthenticatedInventoryOperationsIndexRoute: typeof AuthenticatedInventoryOperationsIndexRoute
  AuthenticatedSalesNewIndexRoute: typeof AuthenticatedSalesNewIndexRoute
  AuthenticatedInventoryUpdateIdIndexRoute: typeof AuthenticatedInventoryUpdateIdIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedClientsIndexRoute: AuthenticatedClientsIndexRoute,
  AuthenticatedDashboardIndexRoute: AuthenticatedDashboardIndexRoute,
  AuthenticatedInventoryIndexRoute: AuthenticatedInventoryIndexRoute,
  AuthenticatedProfileIndexRoute: AuthenticatedProfileIndexRoute,
  AuthenticatedSalesIndexRoute: AuthenticatedSalesIndexRoute,
  AuthenticatedSettingsIndexRoute: AuthenticatedSettingsIndexRoute,
  AuthenticatedInventoryOperationsIdRoute:
    AuthenticatedInventoryOperationsIdRoute,
  AuthenticatedInventoryOperationsNewRoute:
    AuthenticatedInventoryOperationsNewRoute,
  AuthenticatedClientsNewIndexRoute: AuthenticatedClientsNewIndexRoute,
  AuthenticatedInventoryNewIndexRoute: AuthenticatedInventoryNewIndexRoute,
  AuthenticatedInventoryOperationsIndexRoute:
    AuthenticatedInventoryOperationsIndexRoute,
  AuthenticatedSalesNewIndexRoute: AuthenticatedSalesNewIndexRoute,
  AuthenticatedInventoryUpdateIdIndexRoute:
    AuthenticatedInventoryUpdateIdIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  PortalIndexRoute: PortalIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
